-- MySQL Script generated by MySQL Workbench
-- Tue Sep 10 08:55:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gerenciadefarmacia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gerenciadefarmacia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gerenciadefarmacia` DEFAULT CHARACTER SET utf8 ;
USE `gerenciadefarmacia` ;

-- -----------------------------------------------------
-- Table `gerenciadefarmacia`.`ENDERECOS`
-- -----------------------------------------------------
CREATE TABLE  `gerenciadefarmacia`.`ENDERECOS` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `CEP` VARCHAR(45) NULL,
  `LOGRADOURO` VARCHAR(45) NULL,
  ` BAIRRO` VARCHAR(45) NULL,
  `CIDADE` VARCHAR(45) NULL,
  `UF` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `gerenciadefarmacia`.`PESSOAS`
-- -----------------------------------------------------
CREATE TABLE `gerenciadefarmacia`.`PESSOAS` (
  `ID` int NOT NULL,
  `NOME` VARCHAR(45) NULL,
  `CPF` VARCHAR(45) NULL,
  `TELEFONE` VARCHAR(45) NULL,
  `EMAIL` VARCHAR(45) NULL,
  `NUMERO` VARCHAR(45) NULL,
  `COMPLEMENTO` VARCHAR(45) NULL,
  `DATA_NASC` DATE NULL,
  `SEXO` TINYINT(1) NULL,
  `ENDERECOS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_PESSOAS_ENDERECOS1`
    FOREIGN KEY (`ENDERECOS_ID`)
    REFERENCES `gerenciadefarmacia`.`ENDERECOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `gerenciadefarmacia`.`FUNCIONARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciadefarmacia`.`FUNCIONARIOS` (
  `ID` INT NOT NULL,
  `FUNCAO` VARCHAR(45) NULL,
  `LOGIN` VARCHAR(45) NULL,
  `SENHA` VARCHAR(45) NULL,
  `PESSOAS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_FUNCIONARIOS_PESSOAS1`
    FOREIGN KEY (`PESSOAS_ID`)
    REFERENCES `gerenciadefarmacia`.`PESSOAS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `gerenciadefarmacia`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciadefarmacia`.`CLIENTE` (
  `ID` INT NOT NULL,
  `PESSOAS_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_CLIENTE_PESSOAS1`
    FOREIGN KEY (`PESSOAS_ID`)
    REFERENCES `gerenciadefarmacia`.`PESSOAS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `gerenciadefarmacia`.`PAGAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciadefarmacia`.`PAGAMENTO` (
  `ID` INT NOT NULL,
  `TIPO` VARCHAR(45) NULL,
  `VALOR_RECEBIDO` DOUBLE NULL,
  `TROCO` DOUBLE NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `gerenciadefarmacia`.`VENDAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciadefarmacia`.`VENDAS` (
  `ID` INT NOT NULL,
  `PRECO_TOTAL` DOUBLE NULL,
  `DT_VENDA` DATE NULL,
  `HORARIO` VARCHAR(45) NULL,
  `FUNCIONARIOS_ID` INT NOT NULL,
  `PAGAMENTO_ID` INT NOT NULL,
  `CLIENTE_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_VENDAS_FUNCIONARIOS1`
    FOREIGN KEY (`FUNCIONARIOS_ID`)
    REFERENCES `gerenciadefarmacia`.`FUNCIONARIOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDAS_CLIENTE1`
    FOREIGN KEY (`CLIENTE_ID`)
    REFERENCES `gerenciadefarmacia`.`CLIENTE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENDAS_PAGAMENTO1`
    FOREIGN KEY (`PAGAMENTO_ID`)
    REFERENCES `gerenciadefarmacia`.`PAGAMENTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `gerenciadefarmacia`.`ESTOQUE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciadefarmacia`.`ESTOQUE` (
  `ID` INT NOT NULL,
  `QUANT_MIN` INT NULL,
  `QUANTIDADE` INT NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `gerenciadefarmacia`.`MEDICAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciadefarmacia`.`MEDICAMENTO` (
  `ID` INT NOT NULL,
  `CATEGORIA` VARCHAR(45) NULL,
  `TIPO` VARCHAR(45) NULL,
  `RECEITA` TINYINT(1) NULL,
  `CONTRAINDICACOES` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `gerenciadefarmacia`.`PRODUTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciadefarmacia`.`PRODUTOS` (
  `ID` INT NOT NULL,
  `NOME` VARCHAR(45) NULL,
  `PRECO` DOUBLE NULL,
  `LOTE` DATE NULL,
  `ESTOQUE_ID` INT NOT NULL,
  `MEDICAMENTO_ID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_PRODUTO_ESTOQUE1`
    FOREIGN KEY (`ESTOQUE_ID`)
    REFERENCES `gerenciadefarmacia`.`ESTOQUE` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRODUTOS_MEDICAMENTO1`
    FOREIGN KEY (`MEDICAMENTO_ID`)
    REFERENCES `gerenciadefarmacia`.`MEDICAMENTO` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);





-- -----------------------------------------------------
-- Table `gerenciadefarmacia`.`PRODUTO_VENDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciadefarmacia`.`PRODUTO_VENDIDO` (
  `ID` INT NOT NULL,
  `PRODUTOS_ID` INT NOT NULL,
  `VENDAS_ID` INT NOT NULL,
  `PRECO` DOUBLE NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT `fk_LISTA_PRODUTOS_PRODUTOS1`
    FOREIGN KEY (`PRODUTOS_ID`)
    REFERENCES `gerenciadefarmacia`.`PRODUTOS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LISTA_PRODUTOS_VENDAS1`
    FOREIGN KEY (`VENDAS_ID`)
    REFERENCES `gerenciadefarmacia`.`VENDAS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `gerenciadefarmacia`.`MEDICAMENTO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciadefarmacia`.`MEDICAMENTO` (
  `ID` INT NOT NULL,
  `CATEGORIA` VARCHAR(45) NULL,
  `TIPO` VARCHAR(45) NULL,
  `RECEITA` TINYINT(1) NULL,
  `CONTRAINDICACOES` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));


-- -----------------------------------------------------
-- Table `gerenciadefarmacia`.`ADMINISTRADOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciadefarmacia`.`ADMINISTRADOR` (
  `ID` INT NOT NULL,
  `LOGIN` VARCHAR(45) NULL,
  `SENHA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
